CREATE TABLE Hashtags (
    id INT PRIMARY KEY,
    tag_name VARCHAR(100)
);

INSERT INTO Hashtags (id, tag_name) VALUES
(1, '#nature'),
(2, '#travel'),
(3, '#food'),
(4, '#fitness'),
(5, '#fashion'),
(6, '#art'),
(7, '#music'),
(8, '#photography'),
(9, '#love'),
(10, '#life'),
(11, '#fun'),
(12, '#beautiful'),
(13, '#happy'),
(14, '#summer'),
(15, '#winter'),
(16, '#sun'),
(17, '#moon'),
(18, '#sky'),
(19, '#sea'),
(20, '#mountains'),
(21, '#sunset'),
(22, '#sunrise'),
(23, '#holiday'),
(24, '#adventure'),
(25, '#city'),
(26, '#urban'),
(27, '#landscape'),
(28, '#naturelovers'),
(29, '#explore'),
(30, '#wanderlust'),
(31, '#outdoors'),
(32, '#camping'),
(33, '#hiking'),
(34, '#travelphotography'),
(35, '#naturephotography'),
(36, '#streetphotography'),
(37, '#portrait'),
(38, '#blackandwhite'),
(39, '#vintage'),
(40, '#retro'),
(41, '#sports'),
(42, '#yoga'),
(43, '#wellness'),
(44, '#selfie'),
(45, '#dog'),
(46, '#cat'),
(47, '#pet'),
(48, '#family'),
(49, '#friends'),
(50, '#funny');

select * from Hashtags;